### ISSUE TITLE
How to apply the nowcasting command?

### ISSUE THREAD

**Issue by NMC-DAVE** [metoppv/improver#1699] opened 2022-04-06 09:33 UTC
Hi:
       I want to apply nowcasting cli command. I found there are four functions: 
'nowcast_accumulate, nowcast_extrapolate, nowcast_optical_flow,
nowcast_optical_flow_from_winds' . So what's the differences
between  nowcast_optical_flow and nowcast_optical_flow_from_winds,
What's the order of these four functions? Are there examples to use those functions?
Thanks very much.
                                                                                       Dave

**Comment by bayliffe** [comment] 2022-04-06 10:46
Hi Dave,
I'll try and run through a few things that might help.

- nowcast_optical_flow
  - One of the two ways to calculate advection velocities, following the method in:
    - Bowler, N., Pierce, C. and Seed, A. 2004: Development of a precipitation nowcasting algorithm based upon optical flow techniques. Journal of Hydrology, 288, 74-91.
  - This calculates optical flow velocities between the radar fields at T-1 to T+0 and between the radar fields at T-2 to T-1. An average of the two calculated velocities is returned.
- nowcast_optical_flow_from_winds
  - The alternative method for calculating advection velocities. This works by picking a model wind level (steering flow) and advecting the T-1 radar field to T+0 using these wind velocities. The advected field is then compared to the T+0 radar field and the perturbation to the model wind velocities required to better match the two fields is calculated. The perturbed velocities are returned.
- nowcast_extrapolate
  - Used for precipitation rates. Extrapolates the observed precipitation rate out at the desired time intervals (lead_time_interval) out to a specified maximum lead time (max_lead_time)
- nowcast_accumulate
  - Used for precipitation accumulations. Extrapolates the observed precipitation rate out at 1 minute intervals out to the specified maximum lead time (max_lead_time) and from these calculates accumulations with the specified period (accumulation_period).
  - The user can specify the lead time interval at which they want accumulations to be produced (lead_time_interval). So for example a user might want 15 minute precipitation accumulations, but may wish to produce these every 5 minutes (overlapping); accumulation_period=15, lead_time_interval=5.

The order in which to call the steps is to calculate your advection velocities using one of the optical flow methods and then use the resulting velocities to calculate your outputs; use extrapolate to produce rate fields, and use accumulate to produce accumulation fields.

You'll notice that these steps also require an orographic enhancement field. There are tools to calculate this field within IMPROVER. This calculates the expected component of precipitation over hills / mountains that is triggered by orographic uplift. The radar fields are modified to remove this component before calculating the advection velocities. The reasoning here is that we would not expect to see this component move, it's related to the underlying static terrain. The same orographic enhancement field is also required as input to the extrapolation or accumulation steps as in these we reintroduce this enhancement in the original locations. If you want to simply technically demonstrate that you can string these things together you can create a suitable field of zeros, but note that the advection velocities calculated may be poor.

There's a lot more that can be done, e.g. spatially blending the nowcast fields into model fields to make up for missing areas of radar coverage. Hopefully the above is enough to help you make progress.

**Comment by NMC-DAVE** [comment] 2022-04-06 12:43
> 
Hi bayliffe,
     Thank you for your detailed reply. I learn a lot and make the nowcast processing clear. I want to further understanding of the nowcast_optical_flow_from_winds and orographic enhancement methods. Are there any papers or documents about these methods? Thanks again.
                                                                                                                                                      Dave

**Comment by bayliffe** [comment] 2022-04-07 10:19
@NMC-DAVE I can confirm that there are no documents or papers I can point you to in relation to the `nowcast_optical_flow_from_winds` method. My colleague provided the following comment describing how the method came about:

> It seemed like a sensible idea based on the original optical flow paper (Bowler 2004), as optical flow relies on the assumption of continuity and that the perturbations / movement is smaller than a certain radius, and gets less stable as the displacement between frames gets larger.  It was also attempting to deal with the situation where there isn’t enough rain to reliably calculate an advection velocity

Hopefully all of the above has been useful. If you have enough information for now, please close this issue.

Regards,
Ben

**Comment by bayliffe** [comment] 2022-04-19 06:30
There has been no further correspondence. Closing this issue.

**Closed by bayliffe** 2022-04-19 06:30 UTC
